---
- name: Touch a /tmp file
  hosts: all
  tasks:
  - name: Create a temp file
    tempfile: 
      state: file
      suffix: test
    delegate_to: localhost
  - name: Show dir
    shell: find /
    register: foutput
    delegate_to: localhost
  - name: show it
    debug: msg=foutput.stdout
 
